# Generated by Django 5.0.4 on 2024-05-29 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_client_animal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('observacao', models.CharField(blank=True, max_length=150, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.animal')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.servico')),
            ],
        ),
    ]
