# Generated by Django 5.0.4 on 2024-07-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.animal'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamento.servico'),
        ),
    ]
