# Generated by Django 5.0.4 on 2024-06-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cliente", "0002_remove_client_nome_remove_client_sobrenome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="porte",
            field=models.CharField(
                choices=[("P", "Pequeno"), ("M", "Medio"), ("G", "Grnade")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="tipo_pelo",
            field=models.CharField(
                choices=[("L", "Longo"), ("C", "Curto")], default="C", max_length=1
            ),
        ),
    ]
