# Generated by Django 5.0.4 on 2024-06-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_client_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='porte',
            field=models.CharField(max_length=10),
        ),
    ]
